### Grouped by year of review {#sec-subgroup-nodrop-glmm-year}

```{r lst-subgroup-nodrop-glmm-year}

report_subgroup(
  tar_read(subgroup_nodrop_glmm)$year,
  tar_read(meta_subgroup_nodrop_glmm)$year
)

```

### Grouped by continent {#sec-subgroup-nodrop-glmm-continent}

```{r lst-subgroup-nodrop-glmm-continent}

report_subgroup(
  tar_read(subgroup_nodrop_glmm)$continent,
  tar_read(meta_subgroup_nodrop_glmm)$continent
)

```

### Grouped by region {#sec-subgroup-nodrop-glmm-region}

```{r lst-subgroup-nodrop-glmm-region}

report_subgroup(
  tar_read(subgroup_nodrop_glmm)$region,
  tar_read(meta_subgroup_nodrop_glmm)$region
)

```

### Grouped by criteria {#sec-subgroup-nodrop-glmm-criteria}

```{r lst-subgroup-nodrop-glmm-criteria}

report_subgroup(
  tar_read(subgroup_nodrop_glmm)$clean_criteria,
  tar_read(meta_subgroup_nodrop_glmm)$clean_criteria
)

```

### Grouped by instrument {#sec-subgroup-nodrop-glmm-instrument}

```{r lst-subgroup-nodrop-glmm-instrument}

report_subgroup(
  tar_read(subgroup_nodrop_glmm)$clean_instrument,
  tar_read(meta_subgroup_nodrop_glmm)$clean_instrument
)

```

