### Grouped by year of review {#sec-subgroup-trim-glmm-year}

```{r lst-subgroup-trim-glmm-year}

tryCatch(
  report_subgroup(
    tar_read(subgroup_trim_glmm)$year,
    tar_read(meta_subgroup_trim_glmm)$year
  ),
  error = \(e) paste(e)
)

```

### Grouped by published year {#sec-subgroup-trim-glmm-incl-year}

```{r lst-subgroup-trim-glmm-incl-year}

tryCatch(
  report_subgroup(
    tar_read(subgroup_trim_glmm)$incl_year,
    tar_read(meta_subgroup_trim_glmm)$incl_year
  ),
  error = \(e) paste(e)
)

```

### Grouped by continent {#sec-subgroup-trim-glmm-continent}

```{r lst-subgroup-trim-glmm-continent}

report_subgroup(
  tar_read(subgroup_trim_glmm)$continent,
  tar_read(meta_subgroup_trim_glmm)$continent
)

```

### Grouped by region {#sec-subgroup-trim-glmm-region}

```{r lst-subgroup-trim-glmm-region}

report_subgroup(
  tar_read(subgroup_trim_glmm)$region,
  tar_read(meta_subgroup_trim_glmm)$region
)

```

### Grouped by criteria {#sec-subgroup-trim-glmm-criteria}

```{r lst-subgroup-trim-glmm-criteria}

report_subgroup(
  tar_read(subgroup_trim_glmm)$clean_criteria,
  tar_read(meta_subgroup_trim_glmm)$clean_criteria
)

```

### Grouped by instrument {#sec-subgroup-trim-glmm-instrument}

```{r lst-subgroup-trim-glmm-instrument}

report_subgroup(
  tar_read(subgroup_trim_glmm)$clean_instrument,
  tar_read(meta_subgroup_trim_glmm)$clean_instrument
)

```

