### Grouped by year of review {#sec-subgroup-sub-year}

```{r lst-subgroup-sub-year}

report_subgroup(
  tar_read(subgroup_sub)$year,
  tar_read(meta_subgroup_sub)$year
)

```

### Grouped by published year {#sec-subgroup-sub-incl-year}

```{r lst-subgroup-subincl-year}

report_subgroup(
  tar_read(subgroup_sub)$incl_year,
  tar_read(meta_subgroup_sub)$incl_year %>% {.[order(.$Group, decreasing = FALSE), ]}
)

```

### Grouped by continent {#sec-subgroup-sub-continent}

```{r lst-subgroup-sub-continent}

report_subgroup(
  tar_read(subgroup_sub)$continent,
  tar_read(meta_subgroup_sub)$continent
)

```

### Grouped by region {#sec-subgroup-sub-region}

```{r lst-subgroup-sub-region}

report_subgroup(
  tar_read(subgroup_sub)$region,
  tar_read(meta_subgroup_sub)$region
)

```

### Grouped by criteria {#sec-subgroup-sub-criteria}

```{r lst-subgroup-sub-criteria}

report_subgroup(
  tar_read(subgroup_sub)$clean_criteria,
  tar_read(meta_subgroup_sub)$clean_criteria
)

```

### Grouped by instrument {#sec-subgroup-sub-instrument}

```{r lst-subgroup-sub-instrument}

report_subgroup(
  tar_read(subgroup_sub)$clean_instrument,
  tar_read(meta_subgroup_sub)$clean_instrument
)

```


### Grouped by quality {#sec-subgroup-sub-quality}

```{r lst-subgroup-sub-quality}

report_subgroup(
  tar_read(subgroup_sub)$quality,
  tar_read(meta_subgroup_sub)$quality
)

```

