### Grouped by year of review {#sec-subgroup-nodrop-year}

```{r lst-subgroup-nodrop-year}

report_subgroup(
  tar_read(subgroup_nodrop)$year,
  tar_read(meta_subgroup_nodrop)$year
)

```

### Grouped by published year {#sec-subgroup-nodrop-incl-year}

```{r lst-subgroup-nodropincl-year}

report_subgroup(
  tar_read(subgroup_nodrop)$incl_year,
  tar_read(meta_subgroup_nodrop)$incl_year
)

```

### Grouped by continent {#sec-subgroup-nodrop-continent}

```{r lst-subgroup-nodrop-continent}

report_subgroup(
  tar_read(subgroup_nodrop)$continent,
  tar_read(meta_subgroup_nodrop)$continent
)

```

### Grouped by region {#sec-subgroup-nodrop-region}

```{r lst-subgroup-nodrop-region}

report_subgroup(
  tar_read(subgroup_nodrop)$region,
  tar_read(meta_subgroup_nodrop)$region
)

```

### Grouped by criteria {#sec-subgroup-nodrop-criteria}

```{r lst-subgroup-nodrop-criteria}

report_subgroup(
  tar_read(subgroup_nodrop)$clean_criteria,
  tar_read(meta_subgroup_nodrop)$clean_criteria
)

```

### Grouped by instrument {#sec-subgroup-nodrop-instrument}

```{r lst-subgroup-nodrop-instrument}

report_subgroup(
  tar_read(subgroup_nodrop)$clean_instrument,
  tar_read(meta_subgroup_nodrop)$clean_instrument
)

```

### Grouped by quality {#sec-subgroup-nodrop-quality}

```{r lst-subgroup-nodrop-quality}

report_subgroup(
  tar_read(subgroup_nodrop)$quality,
  tar_read(meta_subgroup_nodrop)$quality
)

```

