---
author: Aly Lamuri
title: Meta-Analysis on Selected Articles
format:
  pdf:
    keep-tex: true
    number-sections: true
bibliography: ref.bib
knitr:
  opts_chunk:
    echo: false
    error: false
    warning: false
    message: false
    fig.width: 10
    fig.height: 8
    comment: "|"
header-includes:
- \usepackage{typearea}
---

```{r init}

pkgs <- c("magrittr", "targets", "kableExtra")
pkgs_load <- sapply(pkgs, library, character.only = TRUE)

options(digits = 2)
options(knitr.kable.NA = "")

report_bias <- function(bias) {
  res <- bias %>%
    subset(select = -c(tau, Rb)) %>%
    kable(booktabs = TRUE, longtable = TRUE, escape = FALSE, col.names = c(
      "Label", "K", "$\\beta$", "SE", "$p$", "$I^2$ (\\%)", "$H^2$", "$\\tau^2$"
    )) %>%
    add_header_above(c(" " = 2, "Egger's test" = 3, "Heterogeneity [95% CI]" = 3)) %>%
    kable_styling(font_size = 7, latex_options = c("repeat_header"))

  return(res)
}

report_meta <- function(meta) {
  sub_meta <- meta %>% subset(!.$Exclude, select = -c(Exclude))
  to_bold  <- sub_meta %>% {which(.$Author %in% c("Random", "Fixed"))}
  to_color <- sub_meta %>% {which(.$Author == "Prediction")}
  res <- sub_meta %>%
    kable(booktabs = TRUE, longtable = TRUE) %>%
    add_header_above(c(" " = 3, "Prevalence" = 4, "Weight (%)" = 2)) %>%
    row_spec(to_bold, bold = TRUE) %>%
    row_spec(to_color, bold = TRUE, background = "#D8DEE9") %>%
    kable_styling(font_size = 7, latex_options = c("repeat_header"))

  return(res)
}

getES <- function(meta, type = "Random") {
  sub_meta <- meta %>% subset(.$Author == type)
  return(sub_meta)
}

reportES <- function(ES) {
  msg <- sprintf("%s%% [%s%%; p %s]", round(ES$`%`, 2), ES$`95% CI`, ES$p)
  return(msg)
}

n_eda <- sapply(tar_read(bias_eda), \(x) sum(x$N))

es_all <- getES(tar_read(meta_all)) %>% reportES()

es_eda <- lapply(tar_read(meta_eda), getES) %>%
  lapply("[[", "%") %>%
  sapply(mean)

es_author <- getES(tar_read(meta_author)) %>%
  extract2("%") %>%
  mean(na.rm = TRUE)

tar_load(meta_reg)

```

## Executive Summary {-}

{{< include executive-summary.qmd >}}

{{< pagebreak >}}

## Re-analysis of Included Reviews

{{< include reanalysis.qmd >}}

{{< pagebreak >}}

## Exploratory Data Analysis

{{< include eda.qmd >}}

## Sub-group Meta Analysis, Inverse-Variance Method {#sec-subgroup}

```{r fun-subgroup}

report_subgroup <- function(mod, meta) {
  note <- sprintf(
    "Random model: Q = %s, df = %s, p = %s. Common model: Q = %s, df = %s, p = %s",
    round(mod$Q.b.random, 2),
    round(mod$df.Q.b.random, 2),
    round(mod$pval.Q.b.random, 3),
    round(mod$Q.b.common, 2),
    round(mod$df.Q.b.common, 2),
    round(mod$pval.Q.b.common, 3)
  )

  res <- meta %>%
    kable(booktabs = TRUE, longtable = TRUE, escape = FALSE, col.names = c(
      "Label", "K", "Fixed (\\%)", "Random (\\%)", "$I^2$ (\\%)", "$H^2$", "$\\tau^2$"
    )) %>%
    add_header_above(c(" " = 2, "Prevalence [95% CI]" = 2, "Heterogeneity" = 3)) %>%
    footnote(general = note, general_title = "Between group differences") %>%
    kable_styling(font_size = 10, latex_options = c("repeat_header"))
  return(res)
}

```

{{< include subgroup-invar.qmd >}}

## Meta-regression, Inverse-Variance Method {#sec-metareg}

{{< include metareg-invar.qmd >}}

## Sub-group Meta Analysis, GLMM Method {#sec-subgroup-glmm}

{{< include subgroup-glmm.qmd >}}

### Grouped by criteria {#sec-subgroup-glmmcriteria}

{{< include subgroup/glmm-criteria.qmd >}}

## Meta-regression, GLMM Method {#sec-subgroup-glmm}

{{< include metareg-glmm.qmd >}}

